### ISSUE TITLE
Inclusive true and font face issue

### ISSUE THREAD

**Issue by albertogasparin** [mihhail-lapushkin/grunt-css-url-embed#22]
First of all: `inclusive` option rocks! It allows me quickly to define which image should be converted.
However, the comment solution does not play well with Libsass, especially when it is inside a `@font-face` rule.

``` css
@font-face {
  font-family: 'Icons';
  src:url('fonts/Icons.eot') format('embedded-opentype'),
    url('fonts/Icons.woff') /* embed */ format('woff'),
    url('fonts/Icons.ttf') format('truetype');
}
```

No matter what option I give to Libsass and the position of the comment: every comment (even `/*!*/`) gets stripped. So, I would like to ask you if it would be possible to add an additional method to detect which file should be converted.   
What about `myfile.ext#embed` ? The hash should be a safe operator and should solve problems related to comments stripped by pre/post processors in general.
